---
name: Mobile suites
on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      Suite_Name:
        type: choice
        description: 'Job to be run'
        required: true
        options:
          - FunctionalRegressionSuite
          - FunctionalSmokeSuite

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.Suite_Name != ''
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: adopt

      - name: Installing porject dependencies and test
        run: | 
          mvn clean test -DSuite_Name=${{ github.event.inputs.Suite_Name }}
